### ISSUE TITLE
MacOSX

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/eccodes-feedstock#1]
On MacOSX the `gts_ls` test is failing and is skipped during build. ecCodes-devs are informed.

**Comment by kmuehlbauer** [comment]
I tried building on a macbook and tested several things. After many fruitless tries, the `gts_ls` command worked once with the correct output. But I can't reproduce it. Now and before I get this `Abort trap 6` error message. @jakirkham @pelson Any ideas, to further isolate the cause?

**Comment by jakirkham** [comment]
It probably says something about not being able to load a library, right?

The solution is to set a fallback library path. Normally I do this on both Mac and Linux in case we starting see the issue in both cases (even if that is no the case now). Please take a look at this [line]( https://github.com/conda-forge/vigra-feedstock/blob/master/recipe/build.sh#L79 ) (feel free to quote the path there). Also, you will need a branch with this [line]( https://github.com/conda-forge/vigra-feedstock/blob/master/recipe/build.sh#L7 ) and this [line]( https://github.com/conda-forge/vigra-feedstock/blob/master/recipe/build.sh#L17 ).

**Comment by jakirkham** [comment]
Thanks for putting this in an issue, @kmuehlbauer. It now is almost like documentation (which this still needs) where I can refer to it without re-writing it every time. 😄

**Comment by kmuehlbauer** [comment]
I've sorted out all library problems, it doesn't complain about that anymore.

The command `gts_ls` delivers its help message and as I said, it worked once correctly. So, there is something really weird going on. That's why I'm asking if the source of the `trap 6` can be identified (eg. by using some special programs).

**Comment by jakirkham** [comment]
Running `otool -L` on any binary that has dynamic linkage will tell you what it is linked against. That's where I would start.

There is also a `conda inspect` command that can be used on packages, but it's broken IIRC. @ocefpaf, do you remember what versions `conda inspect` works with?

**Comment by ocefpaf** [comment]
> do you remember what versions conda inspect works with?

`conda-build 1.18.2` if I recall correctly.

**Comment by jakirkham** [comment]
That sounds right.

**Comment by kmuehlbauer** [comment]
@jakirkham Do you see anything unusual? Why does zlib doesn't have the @rpath header? Maybe I need to recompile? Why do hdf/netcdf have this additional dot in the path?

```shell
gts_ls:
	@rpath/libeccodes.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libpng16.16.dylib (compatibility version 38.0.0, current version 38.0.0)
	libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/./libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
	@rpath/./libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/./libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libjasper.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
```

**Comment by jakirkham** [comment]
`libz.1.dylib`, did you add it as a dependency?

**Comment by jakirkham** [comment]
The `.` path shouldn't matter.

**Comment by kmuehlbauer** [comment]
Yes I installed it with conda, after it complained about a missing libz.

**Comment by ocefpaf** [comment]
> `libz.1.dylib`, did you add it as a dependency?

Maybe `libpng` should have that as run dependency too. Let me fix that there.

**Comment by jakirkham** [comment]
Is there some way to specify the path to `libz.dylib` in the `configure` step?

**Comment by kmuehlbauer** [comment]
I believe more and more come that this is a problem with the implementation of `gts` within eccodes. gts AFAIK is a bufr flavour, so I decided to use the bufr reader on that file. This works actually, but bufr doesn't know how to fetch the right definition-tables. After outputting a lot of stuff from the gts-file, it also stops with "Abort trap 6" complaining about not finding a specific definition-file.
I'll stop investigating here, the macbook was only borrowed.

**Comment by kmuehlbauer** [comment]
> Is there some way to specify the path to libz.dylib in the configure step?

But it also could be something related to that.

**Comment by jakirkham** [comment]
Could you please PR what you have? We could at least deal with this in Travis or someone else could take a look when they have time.

**Comment by jakirkham** [comment]
Assuming any of it is PRable.

**Comment by kmuehlbauer** [comment]
> Assuming any of it is PRable.

Sorry, I did everything at the command line:

- downloaded miniconda
- created eccodes-env
- installed dependencies within eccodes-env
- downloaded eccodes-sources/test_data
- created build dir
- cmake with args like here
- make
- tested `gts_ls` with the test_data
- exported DYLD_FALLBACK_PATH 
- I also to export ECCODES_DEFINITION_PATH=path/to/eccodes-src/definitions, because boot.def wasn't found

That's all what I did.

**Comment by jakirkham** [comment]
Also, could take a look at this [snippet]( https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/build.sh#L24-L39 ). This removes the pesky `.`s when they show up. It relies on `conda-build` to fix them. If we had to, we could do similar with `libz.dylib`.

**Comment by kmuehlbauer** [comment]
ECMWF opened an [issue](https://software.ecmwf.int/issues/browse/SUP-1627) about that (login needed). 

I reported that we are building on Travis-CI and which MACosx and Xcode Version is used. I also linked the latest travis green built (gts_ls-test disabled).

**Comment by kmuehlbauer** [comment]
see #2

**Comment by kmuehlbauer** [comment]
Closing this, as there is no near-time solution.
