### ISSUE TITLE
FYI: CCSDS encoding patch

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/eccodes-feedstock#10]
Found this patch which corrects/adapts ccsds-encoding. This is just FYI, if some problems with this arise. This should be incorporated with the next eccodes-release.

https://gist.github.com/erget/9664a4307f1ed9092675faee47cbd6df

[Reference document at WMO](https://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-DRMM_Geneva2016/Documents/IPET-DRMM-IV_Doc4-2-1-1_ccsdsValidationReport.docx)

**Comment by kynan** [comment]
This is fixed in ecCodes 2.0

**Comment by kmuehlbauer** [comment]
@kynan Thanks! If you are interested in  helping maintain this recipe here, consider adding yourself to the [maintainers section](https://github.com/conda-forge/eccodes-feedstock/blob/master/recipe/meta.yaml#L43).
