### ISSUE TITLE
ecCodes 2.17.0

### ISSUE THREAD

**Issue by iainrussell** [conda-forge/eccodes-feedstock#100]
Issue:
ecCodes 2.1.70 has been released, but for some reason conda has not picked it up and built with it - perhaps it needs to be done manually, like I've been doing with Metview.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by iainrussell** [comment]
By the way, this is quite urgent because without this ecCodes, the latest Metview will not build!

**Comment by dtip** [comment]
Hmm that's strange. ecCodes 2.16.0 was picked up automatically on the day it was released: https://github.com/conda-forge/eccodes-feedstock/pull/99

I don't see why 2.17.0 would be any different. conda-forge should be able to pick up Metview automatically as well.

This happened to Magics in the past. It could be a similar issue (bot downtime): https://github.com/regro/cf-scripts/issues/722

If this is happening to Metview as well as ecCodes it's definitely worth opening another issue in `cf-scripts` so one of the pros over there can investigate!

**Comment by iainrussell** [comment]
Yes, it is strange - we wondered if maybe conda-forge only automatically picks up hotfix versions, i.e. only the third number changed, but then it wouldn't have picked up 2.16.0. There is also a possibility of our servers misbehaving, but I'd still expect conda-forge to try again if they couldn't connect.
