### ISSUE TITLE
Add Windows builds

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/eccodes-feedstock#3]
In this issue adding a windows build of eccodes is discussed.

**Comment by kmuehlbauer** [comment]
http://stackoverflow.com/questions/36831026/how-can-i-get-a-basic-fortran-file-to-compile-on-windows-mingw-using-cmake

This shows a way of building eccodes on windows. I'm not sure if this way can be done with conda-forge.

**Comment by ocefpaf** [comment]
@kayhayen eccodes needs Fortran? If so you can try `mingwpy`, I had relative success with it.
`Mingw` is also present in conda, but as far as I know it is not recommended. A third option is the new `MSYS2` stuff, but I confess that I have no idea of the maturity and usability. (I will dig the discussions and add links here later today.)

**Comment by kmuehlbauer** [comment]
@ocefpaf eccodes has fortran bindings, for which we would need fortran. But the sole library is pure C/C++ AFAIK. This feedstock is just for the library. We need to add python and fortran feedstocks later, if this here works for all three OS.

The link was just to prove that someone was able to build eccodes on windows

**Comment by StephanSiemen** [comment]
Just a quick note to say that ECMWF plans to work on a Windows port for ecCodes in the first half of 2019. We aim also to have the Windows build work within conda-forge. We will keep you updated through this issue ...

**Comment by kmuehlbauer** [comment]
@StephanSiemen Great! If other maintainers here can be of any help, let us know.

**Comment by kmuehlbauer** [comment]
Seems we are getting close: #60

**Comment by dtip** [comment]
Windows builds are now working: https://confluence.ecmwf.int/display/SUP/2019/02/15/ECMWF+software+under+Windows . I think we can close this issue.

I'll hang around as a maintainer in case I can help with windows-related build problems in the future.

**Comment by kmuehlbauer** [comment]
@dtip Many thanks :+1:  for working on this and welcome as maintainer!
