### ISSUE TITLE
Fortran Support?

### ISSUE THREAD

**Issue by t-brown** [conda-forge/eccodes-feedstock#48]
Feature Request: Fortran Support

<br/>

Would you consider enabling Fortran support for this package?

I see in the [meta.yaml](https://github.com/conda-forge/eccodes-feedstock/blob/00acb3cc8dfe4036623e8594c1fb60669ba218b7/recipe/meta.yaml#L20) that a Fortran compiler is a build requirement. However in the [build.sh](https://github.com/conda-forge/python-eccodes-feedstock/blob/8f789448d14d67b0e094dd8900bd523bf4ee19cc/recipe/build.sh#L48), Fortran support is disabled.

**Comment by kmuehlbauer** [comment]
@t-brown This is somewhat legacy. When creating this package it was thought having this package only provide the library. Then the different language bindings were created using specific feedstocks like `python-eccodes-feedstock`. Obviously there has been no attempt to create a `fortran-eccodes-feedstock`.

Nevertheless this procedure might have changed in the past. @ocefpaf Do you have any knowledge if we should provide an all-in-one package in the future?

**Comment by ocefpaf** [comment]
Splitting the `python-eccodes` was to avoid a huge build matrix due to `numpy` and `python` versions. The former is no longer true but the latter still is. However, adding FORTRAN here in the main lib is OK and we don't need a separated package for that.
