### ISSUE TITLE
Debug DLL on Windows

### ISSUE THREAD

**Issue by nawendt** [conda-forge/eccodes-feedstock#83]
Issue:
I have developed an R package ([nawendt/gribr](https://www.github.com/nawendt/gribr)) that uses eccodes to read GRIB files. Since eccodes has been made available on Windows, I have been trying to build my package on that platform as well. During testing I have been linking to the eccodes DLL in one of my conda environments. The package builds fine on my local machine and on Appveyor. The trouble is that opening a GRIB file causes a crash. The library works fine within the conda environment and the tools will display data within a GRIB file just fine. I know Rtools contains mingw compilers and this is built with MSVC. I did not think that was the problem given that the linker seems to find the symbols just fine when building the package.

What I have attempted to do is build eccodes using the recipe you have here only having a debug version of the DLL get built. Even following the `bld.bat` script, I get errors with cmake (e.g., not being able to replace Windows symlinks). What I would like to have is a debug version of the DLL so I can see where the crashes are happening when opening a GRIB file in R. However, I am not sure it would be a preferable option for a separate debug DLL to be put in its own package here. If nothing else, hopefully you all can point me in the right direction. My apologies if this is not the correct place for this issue.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
curl                      7.65.1               h4496350_0    conda-forge
eccodes                   2.12.3           vc14he0bfa5d_2  [vc14]  conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.5          nompi_hcc15c50_1100    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libcurl                   7.65.1               h4496350_0    conda-forge
libnetcdf                 4.6.2             ha953453_1002    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
tk                        8.6.9             hfa6e2cd_1002    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
            shell level : 1
 populated config files :
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by dtip** [comment]
Hey @nawendt - you might have more luck if you get in touch with ECMWF software support directly at software.support@ecmwf.int

There's good odds they have some internal Windows build documentation which they may be able to share with you.

Reading your issue again - are you saying that your package works fine with ecCodes inside the conda environment but crashes when the conda environment isn't active?

**Comment by nawendt** [comment]
I'll contact them. Thanks. With regard to my R package, it does not work in or out of the conda environment. What does work are the ecCodes binaries (e.g., codes_list, etc.) that have no issues reading the files that fail when using my package. The little bit of debugging with gdb I was able to do seemed to indicated that the crash happens very early when creating a codes_handle for the file being read.

**Comment by dtip** [comment]
Ahh I feel like I've seen this problem before. I think you need to explicitly open the grib file in binary mode. I believe that there's a difference in the way Windows and Unix open files, but by opening the file in binary mode the Windows behaviour becomes identical to the Unix behaviour. Then ecCodes can handle it.

**Comment by nawendt** [comment]
I had thought the same and made sure to double check that I used the "rb" mode for fopen. I've even pulled an example script from the ecCodes site and linked it to the conda-forge ecCodes library and still get the same result with proper binary mode.

**Comment by nawendt** [comment]
It's likely that a debug DLL would not help here. R needs static libraries and not DLLs, preferably built with mingw. Time would be better spent on getting eccodes to build with the mingw toolchain.
